### ISSUE TITLE
Composition - DiagnosticReport alignment

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#11]
Identify which elements of DiagnosticReport and Composition should be aligned and those that might be 'duplicated'

**Comment by gcangioli** [comment]
| Info  | Composition | DiagnosticReport | Notes |
| ------------- | ------------- | ------------- | ------------- |
| Identifier  | identifier | identifier   | Optional for both ? aligned if present ? |
| reference to order/ order group  |  basedOn-order-or-requisition extension	 | basedOn element. Limited to ServiceRequest. What about Order group | to be discussed  |

_<. to be completed .. in progress>_

**Comment by fmacary** [comment]
Item #2: reference to order/ order group. 
It is true that basedOn cannot reference RequestGroup in R4 nor RequestOrchestration in R5.
But basedOn is repeatable. Thus the DiagnosticReport can enumerate the ServiceRequest resources (the tests and batteries) that composed the order group. 
Yet, what DiagnosticReport fails to convey is the identifier of the order group (RequestGroup.identifier in R4 or RequestOrchestration.identifier in R5).

**Comment by fmacary** [comment]
item 4
type of report should use a value set (laboratory report, microbio report, serology report ...) I would leave that door open.

**Comment by gcangioli** [comment]
2023-05-18: add this topic for the next meeting. A proposal based on the XeH will be discussed

**Comment by gcangioli** [comment]
DiagnosticReport.identifier: added this comment to this element.   
"Usually assigned by the Information System of the diagnostic service provider for facilitating the Report search. The order id can be used as one of the Report identifier if only one report is produced for that order."
