### ISSUE TITLE
Support for FHIR Release 5

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#12]
there is a request to consider a R5 Lab Report IGs and not only that based on R4/R4b. (see #2)

- [x] Evaluate if to develop/maintain a FHIR R5 based IG for this guide

**Comment by joofio** [comment]
I suggest a branch synced with master for the work on R5

**Comment by ahenket** [comment]
I'm okay with a synced branch, as it would be too soon to drop R4

**Comment by fmacary** [comment]
Also in favor of a synced R5 branch. It's a good point to propose also an R5 version of the IG. That's part of the STU process.

**Comment by gcangioli** [comment]
R5 branch prepared
