### ISSUE TITLE
value set for report category

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#15]
Identify a value set (or a fixed code for one of the coding ?) for the Composition and DiagnosticReport category

**Comment by kruzikh** [comment]
Composition category seems to be related to the CDA Document Class (according to the example set http://hl7.org/fhir/ValueSet/document-classcodes) and I think that we should use this category meaning for backward compatibility with CDA and XDS profile.  

In case of lab report, only one value is relevant for this purpose, LOINC 26436-6 "Laboratory Studies (set)"

We might discuss if other categorization purposes would be useful or not.

**Comment by gabriel0316** [comment]
I was wondering why only this single value is relevant.
