### ISSUE TITLE
Composition DiagnosticReport linkage

### ISSUE THREAD

**Issue by njnikodym** [hl7-eu/laboratory#16]
@ahenket  and I stumbled upon the following: 

The [Document Bundle spec](http://hl7.org/fhir/R4/documents.html#content) states that it shall contain the Composition resource, and any resources directly or indirectly (e.g. recursively) referenced from it. However, the HL7 EU Laboratory Composition does not satisfy this requirement. DiagnosticReport links to Composition but not the other way around. 

To conform to the Document Bundle specs, we see two options:
1) Bringing back the extension linking from Composition to DiagnosticReport that existed before.
2) Replace the current slicing on .section with one .section for the DiagnosticReport. Or add another .section for the DiagnosticReport.

The added benefit of option 2 is that the Document bundle would be a subset of IPS and this section could cover all direct properties of the DiagnosticReport. For example, right now the conclusion of the DiagnosticReport does not seem to have an obvious place on the Composition level.

**Comment by gcangioli** [comment]
This was one of the open points..  how much we consider acceptable to pre-adopt the R5 rules (see below) .
The document bundle SHALL include only:
- The composition set: The Composition resource, and the resources it links to
- The supporting information: Any resources that are part of the **graph of resources that reference or are referenced** from the composition set, either directly or indirectly (e.g. recursively in a chain)
- Supporting Collateral: A Binary resource containing a stylesheet (as described below)

**Comment by gcangioli** [comment]
the doubt of adding a Composition to DiagnosticReport is that if we do so we will have a circular reference, since in R5 the reference between Composition and DiagnosticReport is from DR to Composition

**Comment by kruzikh** [comment]
As diagnostic report references composition, it fulfills the condition specified for the bundle: 
- The supporting information: Any resources that are part of the graph of resources that **reference** or are referenced from the composition set, either **directly or indirectly** (e.g. recursively in a chain)

So, we are perfectly fine without reference from composition to DR and we are not creating a circular reference, according to my opinion.

**Comment by gcangioli** [comment]
that seems to me the R5 specification.
R4 says "any resources directly or indirectly (e.g. recursively) referenced **from** it"

see https://build.fhir.org/ig/hl7-eu/laboratory/design-choice.html#pre-adoption-of-r5-rules-for-document-bundle for further details

**Comment by njnikodym** [comment]
I understand why the extension to refer to the Composition from the DiagnosticReport has been added. However in this case, the missing link from Composition to DiagnosticReport is the "bigger" problem as it goes against the definition of a FHIR Document in R4. 

The link from Composition to DiagnosticReport could be introduced by adding an additional .section in the Composition for the DiagnosticReport. However, past discussions determined that Composition equals the DiagnosticReport, not a subsection of it. Hence, an extension to reference from Composition to DiagnosticReport becomes necessary to match the R4 definition.

> how much we consider acceptable to pre-adopt the R5 rules (see below) .
Based on the above, I think the best approach would be to include the extension referencing from Composition to DiagnosticReport, and then either:
- Accept the circular referencing, or
- Remove the extension from DiagnosticReport and exclude this adoption from R5.

**Comment by kruzikh** [comment]
Diagnostic report is not directly nor indirectly referenced from the composition. So, if we want to be 100% R4B compliant (and this is for discussion), we would have to accept one of the proposed solutions.

**Comment by gcangioli** [comment]
The pre adoption of R5 rules have been presented to the OO WG at the HL7 WGM in Phoenix and shared with the FHIR-I co-chair. No push-back on it
