### ISSUE TITLE
Revise value set used for DiagnosticReport.code and Composition.type

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#17]
Revise the LabStudyTypesEu value set; it should represent the lab report types.

**Comment by gcangioli** [comment]
Added a new value set and one additional binding

**Comment by gcangioli** [comment]
2023-05-18: Hynek suggests to add some guidance on how to value these elements

**Comment by gcangioli** [comment]
2023-05-18: change the value set used for the additinal binding with more appropriated concepts.

**Comment by rvisinskiene** [comment]
There are few new data elements in the eHN guidelines release 1.1: https://health.ec.europa.eu/system/files/2023-07/ehealth_ehn-lab-results-guideline_en.pdf
One new data element (A.1.8.5) is related to the types: ![image](https://github.com/hl7-eu/laboratory/assets/143107443/08fadcf3-8a05-4fd5-9a28-fc4f326b7245)
1. No mapping for the new data element (A.1.8.5) from eHN guidelines 1.1
2. Both composition.type and DiagnosticReport.code has a binding with 2 value sets, where seems the first is related to A.1.8.1. Document type and the second one is related to A.1.8.5 Study Type.

**Comment by gcangioli** [comment]
2023-09-01 : 
- use category to classify the study for Composition and DR 
- remove the additional binding from the the Composition.type and DR.code
- add as preferred binding to Composition, DR, category. 
- add a slice for observation category

**Comment by gcangioli** [comment]
modified the 

> 2023-09-01 :
> 
> * use category to classify the study for Composition and DR
> * remove the additional binding from the the Composition.type and DR.code
> * add as preferred binding to Composition, DR, category.
> * add a slice for observation category

updated the profiles and the mapping
