### ISSUE TITLE
informationRecipient mapping 

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#21]
Agree on how to map information recipient in FHIR. CH and IT has defined their own extensions, what abut the others ? should we define for the time being an EU extensions ? 

This is not limited to Lab Report but applies also for other kind of documents.

This requires to add this to the EU FHRI IG base profile.

**Comment by gcangioli** [comment]
added extension http://hl7.eu/fhir/StructureDefinition/information-recipient in https://github.com/hl7-eu/laboratory/commit/abea5c5c6c3056131247374eb2c7b9b9161a9b87

**Comment by gcangioli** [comment]
2023-06-09 - keep the intented-recipient as it is now
add to the composition profile-

**Comment by gcangioli** [comment]
https://github.com/hl7-eu/laboratory/commit/e48f12bc5ffe02577a0317f41f1fe3052cf463e1

**Comment by VeraNoPhD** [comment]
we have used Communication resource for recipient information (LV)... O_O 
Seems to be not to popular approach
