### ISSUE TITLE
Review mapping from the eHN guidelines to this guide

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#25]

**Comment by gcangioli** [comment]
Mapping to be reviewed:
Mapping to be created: 

- [ ] A - Laboratory Report	
- [ ] A.1.1, A.1.2 - Subject of care	
- [ ] A.1.3 - Health insurance and payment information	
- [ ] A.1.4 - Information recipient	
- [ ] A.1.5 - Author	
- [ ] A.1.6 - Legal authenticator	
- [ ] A.1.7 - Result validator	
- [ ] A.2,A.3 - Order	
- [ ] A.4 - Specimen information	
- [ ] A.5 - Results data element

**Comment by gcangioli** [comment]
target code should be a path: move FHIR path to the comment

**Comment by rvisinskiene** [comment]
A.4 - Speciment information: A.4.7 Source Device is related to Specimen.collection.extension:R5Specimen-collection-device in the mapping, however according description of "Source Device" in the eHN guidelines:
"Source Device: If the material is not collected directly from the patient but comes from a patient-related object, e.g. a catheter", thus I think it is more related to Specimen.subject.device.type.

**Comment by gcangioli** [comment]
new A1.8 elements added see also https://github.com/hl7-eu/laboratory/issues/17

**Comment by rvisinskiene** [comment]
Changes in the eHN guidelines releases 1.1 vs 1.0:
New data elements are included:
![image](https://github.com/hl7-eu/laboratory/assets/143107443/6139b23a-d571-48dd-9533-b62295f51267)
![image](https://github.com/hl7-eu/laboratory/assets/143107443/a3e130bf-2d68-4468-9465-f516abf8cd89)
![image](https://github.com/hl7-eu/laboratory/assets/143107443/5db2e3fb-7863-4d5e-a181-eead86024cda)
"Report Custodian" - not new, changes in numbering only.
