### ISSUE TITLE
Specify vocabulary binding for Observation code (lab Results)

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#27]
based on @kruzikh note on https://github.com/hl7-eu/laboratory/issues/3

_specify observation.code binding to LOINC and NPU based value sets_

**Comment by danka74** [comment]
Further, the UK uses SNOMED CT for Observation.code and perhaps SNOMED CT should be added as well

**Comment by gcangioli** [comment]
Thanks @danka74 . Please make  a PR as soon you have some artefact ready. Let's discuss then how to use them..

**Comment by danka74** [comment]
Will do, will run and check a build first. I'll be back!

**Comment by kruzikh** [comment]
Should't we review SNOMED CT value set for observation value currently present in the Results Coded Values Laboratory - IPS? 

Now we have this:
- all the codes that are contained in [http://hl7.org/fhir/uv/ips/ValueSet/results-blood-group-uv-ips](http://hl7.org/fhir/uv/ips/STU1.1/ValueSet-results-blood-group-uv-ips.html)
- all the codes that are contained in [http://hl7.org/fhir/uv/ips/ValueSet/results-presence-absence-uv-ips](http://hl7.org/fhir/uv/ips/STU1.1/ValueSet-results-presence-absence-uv-ips.html)
- all the codes that are contained in [http://hl7.org/fhir/uv/ips/ValueSet/results-microorganism-uv-ips](http://hl7.org/fhir/uv/ips/STU1.1/ValueSet-results-microorganism-uv-ips.html)

**Comment by danka74** [comment]
As discussed at the eX-eHealth Lab semantics meeting today, we have a proposal for an either extensible and preferred binding, which likely overlaps with the IPS presence-absence VS. We should review the proposed VS and the IPS ones for consistency.
