### ISSUE TITLE
Revise the proposed Observation result profiles

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#3]

**Comment by kruzikh** [comment]
I propose following changes  to the Laboratory observation profile:
1. specify observation.code binding to LOINC and NPU based value sets
2. set element issued MS flag
3. remove cardinality on performer element (leave MS flag but allow results without performer information - for discussion)

**Comment by gcangioli** [comment]
> I propose following changes to the Laboratory observation profile:
> 
> 1. specify observation.code binding to LOINC and NPU based value sets

created https://github.com/hl7-eu/laboratory/issues/27

> 2. set element issued MS flag

We should in general revise the MS in these profiles, we agreed not to use MS (waiting for obligation). 

> 3. remove cardinality on performer element (leave MS flag but allow results without performer information - for discussion)

ok for me let's discuss next time

**Comment by gcangioli** [comment]
added https://github.com/hl7-eu/laboratory/issues/28

**Comment by gcangioli** [comment]
added https://github.com/hl7-eu/laboratory/issues/30

**Comment by gcangioli** [comment]
2023-06-23: change the performer to 0..*

**Comment by kruzikh** [comment]
@gcangioli Should observation components have the same value[x] constrains as observation itself?

**Comment by gcangioli** [comment]
@kruzikh I don't see why they should not :-)

**Comment by kruzikh** [comment]
@gcangioli Then we should implement it in the IG !

**Comment by rhausam** [comment]
This is an after-the-fact response, but I agree with having the same constraints for both.  And looking at the CI build following Hynek's commit, they appear to be consistent.
