### ISSUE TITLE
Mapping of the eHN element A5.2.3

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#32]
![image](https://github.com/hl7-eu/laboratory/assets/35879607/ec823a84-92d1-4a11-bc33-bb8d5f2fb04f)

@danka74 , @kruzikh please clarify the meaning of the  A5.2.3 sub elements in order to map them appropriately.

**Comment by gcangioli** [comment]
for the time being I  interpreted as follows
![image](https://github.com/hl7-eu/laboratory/assets/35879607/a7bf8d48-b3a3-4949-af54-259987497d5e)

**Comment by gcangioli** [comment]
originalName => string describing the test independently by the coding system used
name => the designation in the chosen coding system
displayName => the designation in the local coding system (if any)

**Comment by kruzikh** [comment]
agree: originalName => string describing the test independently by the coding system used, i.e. Observation.code.text
agree: name => the designation in the chosen coding system, i.e. Observation.code.coding.display
displayName => actually it should be also derived from the code system. I do not see direct equivalent in the coding data type. Maybe, we can map this element to the  Observation.code.coding.display and explain that either full name (in LOINC it would be long-common-name) or a shorter display name (in LOINC it would be SHORTNAME) should be used.

**Comment by gcangioli** [comment]
Coding.display is 0..1, so you cannot use it for _name_ and _displayName_ fields unless:
(a) they refer to different coded concepts, in this case are display of different codings 
(b) are "translations" of the same coded concept and in this case you can use the translation extension (see https://build.fhir.org/ig/HL7/fhir-ips//StructureDefinition-Coding-uv-ips.html). Already adopted by the profile

**Comment by gcangioli** [comment]
Updated the mapping as indicated above. To be reviewed.

**Comment by danka74** [comment]
I think we should consider having two instances of coding, one for the standard code system (NPU or LOINC) and one for any code system, with a slice on code system and version.

So
A.5.2.3.1 name -> Observation.code.text
A.5.2.3.2 originalName -> Observation.code.coding[0].display
A.5.2.3.3 shortName -> Obsevation.code.coding[1].display

...further, the original code can be sent in Observation.code.coding[0].code

/Daniel

**Comment by gcangioli** [comment]
keep this solution and move the case of multiple designation for the same coded concept to the Cross-border guide
