### ISSUE TITLE
Mapping of the eHN element Reporter

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#33]
![image](https://github.com/hl7-eu/laboratory/assets/35879607/56e34db8-5fe0-4317-96da-ddc6d651300b)

(1) the element conveys different participants, attester, interpreter/author. which of them is expected to be represented
(2) How much is this relevant ? (never seen at the level of single test...) are not these kinds of data inferred from the perfomer ?
(1) In any case I'm not able to find a direct mapping in the Observation resource: should we map them at the level of Composition /DR (but we loose the link with the single observation) ? Could be enough to have this at the level of section ?

@danka74 , @kruzikh thoughts ?

**Comment by kruzikh** [comment]
Lab observation could have several participants according to my experience:
- on the observation level:
  - performer: a person, organiztion or both, that performed the test, element should be optional
  - a person that interpretes and/or validates the result: it is being called reporter in the EHN dataset, element should be optional
- on document (report) level:
  - author (of the report): person or information system who assembled the report or its part. Author could be the same as performer of all or some observations. Each report must have at least one author
  - attester: (optional) a person and organization who validated lab report before submission
  - legal authenticator: person legally responsible for the report and its content, usually head of lab department. Each report should have at least 1 legal authenticator (untill we decide to make it optional :-))
I would think of making an extension of the observation to allow use of reporter. I dont think that we can move it to the composition level.

**Comment by gcangioli** [comment]
> * a person that interpretes and/or validates the result: it is being called reporter in the EHN dataset, element should be optional

as I wrote above  _intepreter_ and _attester_ are two distinct participants, which of them are you looking for ?
If both it would be better to make them explicit in the model

**Comment by gcangioli** [comment]
At the implementation level the only solution I see is that of mapping all of them in the perfomer function, taking advantage of the extension performer function (see https://build.fhir.org/ig/HL7/fhir-extensions/StructureDefinition-event-performerFunction.html) 

My question is if this worth ....

**Comment by kruzikh** [comment]
After a discussion (me, Gunnar, Daniel), we agreed that use of the http://hl7.org/fhir/StructureDefinition/event-performerFunction extension might be useful for complex situations. If there will be more then oně performer, we might make this extension mandatory in order to distinguish between different performer roles.

**Comment by gcangioli** [comment]
Added optional extension http://hl7.org/fhir/StructureDefinition/event-performerFunction
set as default value v3-ParticipationType#RESP // Responsible party
