### ISSUE TITLE
Observation lab result: fix the invariant eu-lab-1:

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#34]
Update the invariant to take in account the case of usage of component and the absence of data 
eu-lab-1: if no "hasMember" element is present then Observation must have a" value"

**Comment by gcangioli** [comment]
Call 2023-07-21
proposed invariant 
At least one of these Observation elements shall be provided: "value", "dataAbsentReason", "hasMember" or "component"
: value.exists() or hasMember.exists() or component.exists() or dataAbsentReason.exists()

@kruzikh : in case of registered entries dataAbsentReason could be redundant (just leave observation  empty)
@rhausam : an invariant at the level of component should be added (or value or dataAbsentReason).
NHS: has as invariant value or dataAbsentReason or note

**Comment by gcangioli** [comment]
Options to be considered:
(1) keep as it is
(2) keep as it is if the status is not [registered](http://hl7.org/fhir/R4/codesystem-observation-status.html#observation-status-registered) or [cancelled](http://hl7.org/fhir/R4/codesystem-observation-status.html#observation-status-cancelled)
(3) remove the invariant
(4) other proposals.....


please provide you comments

**Comment by gcangioli** [comment]
added invariant for the component

**Comment by kruzikh** [comment]
I modified the invariant and it should be now ok. 

Invariant: eu-lab-1
Description: "If observation status is other then \"registered\" or \"cancelled\", at least one of these Observation elements shall be provided:  \"value\", \"dataAbsentReason\", \"hasMember\" or \"component\""
Severity: #error
Expression: "status = 'registered' or status = 'cancelled' or value.exists() or hasMember.exists() or component.exists() or dataAbsentReason.exists()"

Invariant: eu-lab-2
Description: "If observation has components and observation status is other then \"registered\" or \"cancelled\", at least one of these Observation.component elements shall be provided:  \"value\" or \"dataAbsentReason\""
Severity: #error
Expression: "component.exists() implies status = 'registered' or status = 'cancelled' or component.value.exists() or component.dataAbsentReason.exists()"

**Comment by kruzikh** [comment]
@gcangioli Can we close this issue?

**Comment by gcangioli** [comment]
> @gcangioli Can we close this issue?

@kruzikh: I suggest to keep it as "to be reviewed" just to have the confirmation by the team that is the invariant the team want.
