### ISSUE TITLE
Clean up the Bundle-BundleHepatitisPanel example

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#37]
fix errors and warning for the Bundle-BundleHepatitisPanel example

|             Filename  | Errors  |          Warnings	| Hints |
|:------------------------------:|:------------:|:------------:|:-----------------------------:|
| Bundle-BundleHepatitisPanel         |       24	|           9          | 22 |

**Comment by declankieran-nhsd** [comment]
Hi @gcangioli 

I ran the publisher through a debugger and it appears to not like `CodeSystem.content` being set to `example` at https://github.com/hl7-eu/laboratory/blob/master/input/fsh/terminologies/lab-localVsCs-lab.fsh#L26

Setting it to `complete` makes all the errors go away, I see experimental is set to `true` as well, so it might be an issue with the publisher...

**Comment by gcangioli** [comment]
thank you @declankieran-nhsd for the indication.

Looking to the definition of the "example" we are not in the case of a "A subset of the **valid externally defined concepts** are included in the code system resource." 

I'll change the setting to "complete" , but I'll leave to @rhausam deciding if to keep it, changing the coded concepts used; or adopting alternative solutions.
