### ISSUE TITLE
Clarify/correct comment on diagnosticReport.identifier

### ISSUE THREAD

**Issue by kruzikh** [hl7-eu/laboratory#43]
I have some doubts on the second sentence in current description of the identifier: 

^comment = "Usually assigned by the Information System of the diagnostic service provider for facilitating the Report search. **The order id can be used as one of the Report identifier if only one report is produced for that order.**"

Could we clarify a bit the meaning of this identifier, recommendations of its use and its relation to the bundle and composition identifier? We should also discuss how the order identifier should be used - in basedOn reference, in report.identifier in one of them or in both places.

**Comment by gcangioli** [comment]
In the call of May 18th, it was highlighted how in the the definition of the DiagnosticReport.identifier it is written that it can be used "making queries about this report from the source laboratory, and for linking to the report outside FHIR context" and it is "Usually assigned by the Information System of the diagnostic service provider (filler id).". Alternate names are: ReportID; Filler ID; Placer ID.

So the general understanding was that this identifier could be also used to convey a filler/placer ID (that is an order ID).

However it cannot be a report identifier if there is not a 1  to 1  relationship between that order ID and the report.

**Comment by gcangioli** [comment]
based on discussion on https://github.com/hl7-eu/laboratory/issues/11 we agreed that Composition and DR identifier shall be aligned

The bundle.identifier is a businees identifer for that specific instance of a diagnostic Report bundle. (in principle you can have more bundles generated form one composition.
