### ISSUE TITLE
DiagnosticReportCompositionR5 cardinality

### ISSUE THREAD

**Issue by rgazzarata** [hl7-eu/laboratory#44]
In DiagnosticReport: Laboratory Report, DiagnosticReportCompositionR5 is indicated as required in Card, but as optional in Description & Constraints. Which one is corrects?

**Comment by gcangioli** [comment]
@rgazzarata : "Optional Extensions Element" is the default short for extensions.. but I agree we need to add a proper short

**Comment by gcangioli** [comment]
@rgazzarata are you ok with the proposed text ?

**Comment by rgazzarata** [comment]
Perfect!
