### ISSUE TITLE
Patient.name.family cardinality

### ISSUE THREAD

**Issue by rgazzarata** [hl7-eu/laboratory#46]
In Description & Constraints of Patient.name is indicated that Patient.name.given, Patient.name.family or Patient.name.text shuld be present, but bellow name.patient is indicated as required. Is it correct?

**Comment by gcangioli** [comment]
@rgazzarata : my apologizes, but I'm not sure to have understood the question. 
Patient.name is required, the invariant says that at least one among given, family or text shall be present. (this is the IPS invariant on name)
There is then an additional constraint that requires the family. This makes the invariant always true (i.e., in some sense the invariant superfluous). However I suggest to keep it, also in the light of [the Relax cardinality of Patient.name.family?](https://github.com/hl7-eu/laboratory/issues/48) issue

**Comment by gcangioli** [comment]
2023-09-01 - No issue.

**Comment by rgazzarata** [comment]
Sorry @gcangioli I have wrong writte. "In Description & Constraints of Patient.name is indicated that Patient.name.given, Patient.name.family or Patient.name.text shuld be present, but bellow **name.family** is indicated as required. Is it correct?" I have seen that now it is **name.family** so for me is ok. Thanks.
