### ISSUE TITLE
Relax cardinality of Patient.name.family?

### ISSUE THREAD

**Issue by ziegm** [hl7-eu/laboratory#48]
We are working on an exchange format for the laboratory report in Switzerland, where we try to be conform to the HL7 Europe Laboratory Report.

For the case of reporting HIV/AIDS there is a rule (by law), which says, that a special combination of the first name (first letter & amount of letters) is required and nothing else is allowed. In the profile [Patient (Identified Person)](https://build.fhir.org/ig/hl7-eu/laboratory/branches/master/StructureDefinition-Patient-eu-lab.html) the rule **eu-pat-1** works, but **Patient.name.family 1..** does not.

Is there any change to relax it to 0 and only have the rule applied, so that we are able to stay conform?

**Comment by gcangioli** [comment]
@ziegm : where is recorded this "special combination of the first name" ?

In general I'm fine with your proposal, we could add the constraint on the family name at the level of cross-border specification.

**Comment by ziegm** [comment]
Documentation on the [website](https://www.bag.admin.ch/bag/de/home/krankheiten/infektionskrankheiten-bekaempfen/meldesysteme-infektionskrankheiten/meldepflichtige-ik.html) of Federal Office of Public Health (FOPH)

[Übersicht Meldepflicht 2023, DE (overview reporting obligation)](https://www.bag.admin.ch/dam/bag/de/dokumente/mt/msys/msys-flyer.pdf.download.pdf/flyer-200120-d.pdf):   
3) bei HIV/Aids unter Initialen den ersten Buchstaben und die Anzahl der Buchstaben des Vornamens eintragen. Falls dieser länger ist als 9 Buchstaben, ist die Zahl 0. Bei mehrteiligen Vornamen mit Bindestrich oder in zwei Wörtern wird nur der erste Teil verwendet.    
3) for HIV/AIDS, under Initials, enter the first letter and the number of letters of the first name. If this is longer than 9 letters, the number is 0. In the case of multi-part first names with a hyphen or in two words, only the first part is used. 

***

We could also use the data-absent-reason extension with the value *masked* for name.family and name.given and put the special value in case of HIV in name.text. That way, no adaptation in eu-lab would be necessaire.   
In any case we would like to have your opinion on it.

**Comment by gcangioli** [comment]
2023-09-01 - relax the constraint to 0.. Henket/Ziegler 17-0-0
