### ISSUE TITLE
Patient.name.family cadinality to allow to inform two family names as Spain use case

### ISSUE THREAD

**Issue by domingomanel** [hl7-eu/laboratory#50]
Currently the patient.name.family cardinality is defined as 0..1 but in Spain we have the use case where the majority os spanish citizens have two family names, so this means from Spain we need the possibility to inform two family names. Could be possible to change the cardinality to 0..N?

**Comment by gcangioli** [comment]
this is due to the fact that patient.name is of type HumanName. 
HumanName has family 0..1

![image](https://github.com/hl7-eu/laboratory/assets/35879607/7aef8c64-fa64-4587-944f-88c7aacff5bb)

**Comment by gcangioli** [comment]
There are some standard extensions can be used to capture additional family names 
![image](https://github.com/hl7-eu/laboratory/assets/35879607/dd261ff8-48e1-40bf-a2e1-85c4e0e5e19a)

**Comment by gcangioli** [comment]
the current profile doesn't avoid to use them when needed

**Comment by domingomanel** [comment]
Dear @gcangioli,

Thanks for the feedback, a question, we are following the same approach for the current european cross border services as ePrescription, PatientSummary, HDR and Image Exchange? (We mean to change the cardinality to 0..1). From Spain we want to avoid to have different cardinalities on this field in every cross border use case...is that the case?

We would apreciate before close the issue to have the opportunity to provide feedback.

Manel Domingo.
Spanish Ministry of Health.

**Comment by kruzikh** [comment]
Hi @gcangioli,
I haven't read this conversation before and I made a change on cardinality of the family name of the patient resource because I thought that it is an error (as cardinality of this element in other MyHealth@EU use cases allows multiple family names). Should I roll it back to 1..1?

**Comment by gcangioli** [comment]
> Thanks for the feedback, a question, we are following the same approach for the current european cross border services as ePrescription, PatientSummary, HDR and Image Exchange? (We mean to change the cardinality to 0..1). From Spain we want to avoid to have different cardinalities on this field in every cross border use case...is that the case?
> 

Hi @domingomanel,

(1) eHN guidelines doesn't specify cardinalities
(2) I agree we need to have harmonized solutions for the same selected technology. In this case don't see an issue of having ...* for the CDA and ...1 for FHIR because this is what each standard allows. For example CDA IPS allows for family ...*, FHIR IPS does not.
(3) Several countries already restrict also for CDA templates family ..1; but for the countries that have different rules we should define in the FHIR representation which name should go in the name.family and which in extensions.

**Comment by gcangioli** [comment]
> Hi @gcangioli, I haven't read this conversation before and I made a change on cardinality of the family name of the patient resource because I thought that it is an error (as cardinality of this element in other MyHealth@EU use cases allows multiple family names). Should I roll it back to 1..1?

based on decision made for https://github.com/hl7-eu/laboratory/issues/48 it should be 0..1

**Comment by kruzikh** [comment]
I propose to re-discuss this topic and give clear guidance how countries allowing multiple family names should implement it in FHIR.

**Comment by gcangioli** [comment]
Hi @domingomanel ,
if you put these extensions as mandatory (i.e. cardinality 1..) you impose to have multiple family names also for the countries having only one :-)

What the CDA 1..* says is that you need to provide at least one; this is the constraint that will be applied for the MyHealth@EU Lab Report IG

What we can impose is that the receivers should be able to handle such a kind of extensions. This will be done by using a new FHIR IG feature under development called "Obligation"

**Comment by jdeloscobos** [comment]
One topic for this New profile if you agree
I think the fields must be without s, motherName instead of mothersName,  and including in URL type, because can confuse about the cardinales. Thanks

**Comment by domingomanel** [comment]
> Hi @domingomanel , if you put these extensions as mandatory (i.e. cardinality 1..) you impose to have multiple family names also for the countries having only one :-)
> 
> What the CDA 1..* says is that you need to provide at least one; this is the constraint that will be applied for the MyHealth@EU Lab Report IG
> 
> What we can impose is that the receivers should be able to handle such a kind of extensions. This will be done by using a new FHIR IG feature under development called "Obligation"

Hi @gcangioli !

First of all thanks for your feedback and invest time to try to find the best approach. 

I understand the scope to build this European IG as more flexible as possible, and added to that you mentioned me this IG scope, is not just for human being is not for other potential jurisdiction use cases...

Knowing in the MyHealth@EU Lab Guilines we will change the cardinality to 1.. it let me quite, and not just that if not also knowing we can put that "obligation" constraint to require to handle the family names extension to other countries (also in the EU Lab Guideline) 

I think we have found more or less a potential solution that can be used for every family names use cases (as Spain)

Again Giorgio, thank you for support us on this.

Manel.
Spanish Ministry of Health.

**Comment by domingomanel** [comment]
> One topic for this New profile if you agree I think the fields names must be firstSurnane and secondSurname because we need to take into account the parents with the same sex. Thanks

@gcangioli,

When you have a moment, please, could you check if for you make sense what Juan is suggesting?

Thanks in advance.
Best Regards.

Manel.
Spanish Ministry of Health.

**Comment by gcangioli** [comment]
> One topic for this New profile if you agree I think the fields names must be firstSurnane and secondSurname because we need to take into account the parents with the same sex. Thanks

Hi @jdeloscobos I totally agree with your statement :-) unfortunately these are the names given to these standard extensions. 

![image](https://github.com/hl7-eu/laboratory/assets/35879607/4f92b611-8160-437d-acb8-9f489a3acafb)

What we can do (since it is allowed) is to give the option to have more than one (e.g. have two fathers or two mothers) . 
In that case should we add the invariant that the sum of the elements should not exceed two ?

**Comment by gcangioli** [comment]
.. not a perfect solution.. but an option

**Comment by lisaFHI** [comment]
We have had a dozen discussions about names in Norway as well. We often have what we call a "middelname" - family names that are not considered Family name. We ended up using Given - to add all the first names, all the middelname and reserve family name for one name only. This because we checked the legal aspect in Norway that says only one family name is allowed.
For more information: https://simplifier.net/hl7norwayno-basis/nobasishumanname
Is multiple family names allowed legally in Spain?

**Comment by domingomanel** [comment]
Hi @lisaFHI,

In Spain is totally legal to have two family names, and not just that, if not is the standard in any Spanish citizen born in Spain from Spanish parents.

Just check my name or @jdeloscobos complete names:

Manel (given) Domingo (first family name heritated from father first name) Falcón (second heritated from first mother name)
Juan (given) de los Cobos (first family name heritated from father first name) Molina (second heritated from first mother name) 

I hope this helps.

Best Regards.

Manel.
Spanish Ministry of Health.

**Comment by domingomanel** [comment]
> > One topic for this New profile if you agree I think the fields names must be firstSurnane and secondSurname because we need to take into account the parents with the same sex. Thanks
> 
> Hi @jdeloscobos I totally agree with your statement :-) unfortunately these are the names given to these standard extensions.
> 
> ![image](https://user-images.githubusercontent.com/35879607/269252951-4f92b611-8160-437d-acb8-9f489a3acafb.png)
> 
> What we can do (since it is allowed) is to give the option to have more than one (e.g. have two fathers or two mothers) . In that case should we add the invariant that the sum of the elements should not exceed two ?

@gcangioli, we have discussed this topic with @jdeloscobos and what we have concluded is that for uses cases as we have in Spain (two mandatory family names), is not needed to put 0..* cadinality in that fields (fathersName, mothersName), because the first family name in every case will be informed in the field "family" we have in the standard patient resource definition...so just we will use this extension to inform the second family name, so based on this, in case the second family could come from "another" father / man we could inform the second family name in the field fathersFamilyName, and in case the second family name comes from the mother, wil be informed in the mothersFamilyName.

Summarizing, we can keep the cardinality of these fields to: 0..1

I hope this helps!

Manel.
Spanish Ministry of Health.

**Comment by gcangioli** [comment]
@jdeloscobos and @domingomanel ,

- the current proposal is to use in name.family for the full family name (e.g.  "Domingo Falcón") this will allow the other receiving countries to treat this as a single name. For example if you need to be recorded in an Italian or a Norvegian record , I suppose you'd like to be recorded as "Domingo Falcón" and not only "Domingo".
- The extension can (or shall depending on the jurisdiction) be used to indicate what is the mother (Falcon) and the father (Domingo) names. What I was told is that the order in the family gives the first and the second name.  By default the first comes form the father and the second from the mother, but a citizen can determine which should be the first (or even decide not to use one of them and take first and second from the mother).
- These extensions must be properly handled/displayed by the receivers

Is this in line what you were thinking ?

**Comment by gcangioli** [comment]
for the two mothers case: in your view only the second family name (as mother's family name) should be captured when you say 0..1 is enough ?

**Comment by gcangioli** [comment]
added a zulip thread in the Europe stream https://chat.fhir.org/#narrow/stream/242580-europe/topic/Multiple.20family.20names

**Comment by gcangioli** [comment]
added a zulip thread in the Patient Amdin stream https://chat.fhir.org/#narrow/stream/179254-patient-administration-WG/topic/Multiple.20family.20names

**Comment by costateixeira** [comment]
The extensions would be useful to say "This part of the name is from the mother" and "this part of the name is from the father" - noting that we may have same-sex couples and there's really no single way to handle it. Also people may choose to take or not the spouse's names. Each of those names can have several words.

So, a name would be expressed as 
* family name = "da Costa Teixeira"
* extension:mother = "da Costa" 
* extension: father = "Teixeira"
* extension:partner = ...

With this, I don't see the need to make family name 0..* - it's a string. If we want to decompose it, we can always do it.
Making it 0..* could actually cause confusion in how to present them: "Teixeira da Costa" or "da Costa Teixeira" - those are different things.
As long as we clarify that that the name is not limited to one word, I think we are ok - also for EU citizens that have e.g. Chinese or Vietnamese names. 

So I see this as working ok as is, from an interface perspective

**Comment by gcangioli** [comment]
@costateixeira the point it is not to make family 0..* but how to use at the best the existing extensions to manage this case and give common rules for using them :-)

**Comment by domingomanel** [comment]
> @jdeloscobos and @domingomanel ,
> 
> * the current proposal is to use in name.family for the full family name (e.g.  "Domingo Falcón") this will allow the other receiving countries to treat this as a single name. For example if you need to be recorded in an Italian or a Norvegian record , I suppose you'd like to be recorded as "Domingo Falcón" and not only as "Domingo".
> * The extension can (or shall depending on the jurisdiction) be used to indicate what is the mother (Falcon) and the father (Domingo) names. What I was told is that the order in the family gives the first and the second name.  By default the first comes form the father and the second from the mother, but a citizen can determine which should be the first (or even decide not to use one of them and take first and second from the mother).
> * These extensions must be properly handled/displayed by the receivers
> 
> Is this in line with what you were thinking ?

Hi @gcangioli,

The topic on this is the following, let's imagine you use the standard family name for example for @jdeloscobos first family name + second family: "de los Cobos Molina", in that case how you will able to identify what part of that family name field is the fist family name and what is the second family name.

In the past in Spain from in HL7 v2.x from HL7 Spain, we defined a specific "Z" segment just to inform the second family name, for that reason we were thinking to use just to use the standar patient.name. family for the first family name and the extension por the second family name...because for our systems is very important be able to handle easy what are the first and second family name...

Apart of the topic if the patient has two mothers or two father, another thing is if we define as best practice to inform the fields as @costateixeira is suggesting or not....our opinion is that not make sense because we are duplicating information inside the same patient resource.

I hope this helps.

Manel.
Spanish Ministry of Health.
