### ISSUE TITLE
Measurement uncertainty

### ISSUE THREAD

**Issue by kruzikh** [hl7-eu/laboratory#54]
@gcangioli Should we explicitly add extension for uncertainty of measurement to the Quantity data type?

http://hl7.org/fhir/StructureDefinition/iso21090-uncertainty

**Comment by gcangioli** [comment]
@kruzikh I'd say yes as optional extension.

**Comment by gcangioli** [comment]
@kruzikh only quantity may have uncertainty or also other kinds of measures (e.g. ratio, range,....) may ?

**Comment by kruzikh** [comment]
@gcangioli, you are right, uncertainty of measurement can be used also for other types of quantity. I will prepare a new commit.
