### ISSUE TITLE
Review the Laboratory Report page and menu

### ISSUE THREAD

**Issue by gcangioli** [hl7-eu/laboratory#55]
- Review the Laboratory Result Report (semantic-notes.html page)
- possibly split in more pages
- reorganize the menu entry (the current name is quite generic)

**Comment by gcangioli** [comment]
@kruzikh : check if you are OK with the applied changes

**Comment by kruzikh** [comment]
@gcangioli it look good. I just noticed that you renamed value sets by adding Vs to the name - I agree. I would also propose to change names of logical model by adding Lm into their names.
