### ISSUE TITLE
Bundle idenfitier cardinality

### ISSUE THREAD

**Issue by rgazzarata** [hl7-eu/laboratory#57]
From the bundle specification (https://hl7.org/fhir/R4/bundle.html) it seams that if the bundle is a document, it must have an identifier (bdl-9), so the cardinality of bundle.identifier should be 1..1

**Comment by gcangioli** [comment]
Grazie @rgazzarata . 

In principle this constraint is covered by the invariant, however I agree that is worth to make it explicit.

**Comment by gcangioli** [comment]
fixed in https://github.com/hl7-eu/laboratory/commit/24c7fe196cb762e69e56de576af7e16290fe1cfe
