### ISSUE TITLE
Name convention issues in the ballot

### ISSUE THREAD

**Issue by igorboss** [hl7-eu/laboratory#65]
- Attribute in the custom datatype uses the wrong name convention. For example:
  - https://build.fhir.org/ig/hl7-eu/laboratory/branches/master/StructureDefinition-Address-eu.html: "Streetname" -> should be "streetName"
  - https://build.fhir.org/ig/hl7-eu/laboratory/branches/master/StructureDefinition-Ratio-eu-lab.html: "Uncertainty" -> should be "uncertainty".

**Comment by gcangioli** [comment]
Reported in Jira as [FHIR-42992 Name convention issues in the ballot](https://jira.hl7.org/browse/FHIR-42992)

**Comment by igorboss** [comment]
Let's switch to Jira
