### ISSUE TITLE
Issues with logical models and mappings in the Ballot

### ISSUE THREAD

**Issue by igorboss** [hl7-eu/laboratory#66]
- Logical models do not have examples
- Logical models have not-optimal structure
  - For example [Order](https://build.fhir.org/ig/hl7-eu/laboratory/branches/master/StructureDefinition-Order.html)
    - probably should have cardinality 0..* for “orderDetails” and most of subattributes should have cardinality 0..1 (at least dateTime)
    - reason is 0..* BackboneElement and have code 0..* CodeableConcept. reason 0..* CodeableConcept should be enough.
  - Please see the example of the FML transformation I created https://termx.kodality.dev/modeler/transformation-definitions/161/edit. The writing of FML transformation was not natural for this model. I created an example for transformation, and if you add new elements to arrays, the result of the transformation will be unexpected (that forward to the model problems).
- The transformations of logical models to the profile written in the ConceptMap and, as a result contains many problems
  - for example, [Order model to this guide](https://build.fhir.org/ig/hl7-eu/laboratory/branches/master/ConceptMap-order2FHIR-eu-lab.html) 
    - ServiceRequest.identifier and ServiceRequest.requisition both mapped to Order.orderDetails.identifier without specifying of identifier system
    - ServiceRequest.requester is Reference and ServiceRequest.requester.name, ServiceRequest.requester.practictioner, ServiceRequest.requester.telecom, ServiceRequest.requester.address doesn’t exists
    - ServiceRequest.reasonCode mapped to Order.reason (A.3 Order reason), but Order.reason is BackboneElement
  - I recommend using of StructureMap (FML mapping) to prevent such kind of errors

**Comment by gcangioli** [comment]
Copied in jira as:

- https://jira.hl7.org/browse/FHIR-42993
- https://jira.hl7.org/browse/FHIR-42994
- https://jira.hl7.org/browse/FHIR-42995

**Comment by igorboss** [comment]
Let's switch to Jira
